### ISSUE TITLE
ISSUE INTEGRATION GOG GALAXY OF PLAYSTATION

### ISSUE THREAD

**Issue by bportalanza** [FriendsOfGalaxy/galaxy-integration-psn#40]
**Describe the bug**
it Shows the next error: "A connection to the server could not be established.
(18.66721cb8.1654455057.1b738a06)" when it asks my credencials 

**To Reproduce**
Steps to reproduce the behavior,:
1. Log in with account that have Playstation on gog integration
2. It shows: "A connection to the server could not be established.
(18.66721cb8.1654455057.1b738a06)"

**Expected behavior**
Connect Playstation integration on GOG galaxy.

**Comment by ivanrayner** [comment]
Do you have 2 Step Verification enabled on your PSN account?  If so, have you tried disabling it?

**Comment by mcgowan7** [comment]
I found this because I have same issue. I just disabled 2-factor and still Offline - Retry and Disconnected

**Comment by gnoling** [comment]
Same. I don't believe the developer maintains this integration anymore, so here's hoping someone figures out a solution.

**Comment by finkleroy** [comment]
I'm having the same issue. Is there another PSN integration we can use instead of this one?

**Comment by FiftyFour7250** [comment]
Same. Fix please.

**Comment by BaumherA** [comment]
Did some digging. This does not appear to be an issue with the integration here. I believe this is an issue with the Galaxy Client. 
Without getting overly technical, the Authentication URL obtained from here https://github.com/FriendsOfGalaxy/galaxy-integration-psn/blob/a769b09431ed3584557c5e10ce7855c1c4848388/src/http_client.py#L7-L15 resolves to the following:

https://web.np.playstation.com/api/session/v1/signin?redirect_uri=https://io.playstation.com/central/auth/login%3FpostSignInURL=https://www.playstation.com/%26cancelURL=https://www.playstation.com/&smcid=web:pdc

if you paste this into your browser of choice, you can try logging in directly. if you can do so, this is not an issue with this integration, but rather an issue with the Galaxy Client. if you get that same error in your browser, it is an issue on Sony's end. If that url results in a 404 page or something of the like, that is an issue with that link. 

For me, i can successfully log in via that url, using Edge version 103 (the current version as of this writing) It may be worth noting that i have to do a verification quiz. This quiz does not pop up in the GOG Galaxy.

**Comment by BaumherA** [comment]
A more technical note: Your login information is stored via a 64-bit cookie, known as a "session cookie". this cookie expires relatively quickly. However, there's a second cookie, called a "refresh cookie" that allows the caller to obtain a new "session cookie." After a period of two months of inactivity, the "refresh cookie" also expires. you will need to reauthenticate when that happens. if you access GoG Galaxy fairly often, this likely won't be an issue. The application checks if you have a session cookie, and if it has expired, attempts to retrieve a new one via the refresh cookie. if that has also expired, you need to log in again. The integration returns a "NextStep" object when this occurs. This tells the Galaxy to display a webpage (that URL in the previous comment), and, should you login successfully, take those cookies and pass them back to the plugin. The plugin never gets those cookies because the login never succeeds. 
The error you are seeing is most likely a security issue raised by PSN because the integrated browser Galaxy Client uses is out of date. I cannot confirm this because i do not have the source code for the client and do not know what integrated browser they use. It may also be an issue of PSN being down, either in your region or for maintenance. 

I have submitted a bug report to GoG outlining this. If it is a browser issue, updating it would fix the issue. I'd like to test further, but upon trying earlier today, it suddenly worked again. The only thing i can suggest for now is to try logging in again later, but hopefully this can get fixed in the client. 

Alternatively, you can try logging in via the link and manually copying the 64 bit cookie into the plugin.py authenticate function, but i really do not recommend this. It will expire very frequently and thus be pretty pointless. You also should only do so if you know what you're doing. I believe this method is outlined in the GoG Galaxy Integration page for this issue

**Comment by finkleroy** [comment]
I'm able to successfully login using the second link you provided. I'm also able to login using the Playnite client, so it appears the issue is indeed with the Galaxy client. We'll need for GOG to fix it.

**Comment by BaumherA** [comment]
> I'm able to successfully login using the second link you provided. I'm also able to login using the Playnite client, so it appears the issue is indeed with the Galaxy client. We'll need for GOG to fix it.

In the event GoG dev team sees this, what OS do you use, Which browser did you try it with, and what Region are you from? Any information we can provide may be useful. For region, the language/country code on Sony's website is likely enough, if you feel comfortable sharing it. Ideally, if you are testing via Firefox (i.e. not Chromium-based), that would be new information, but i guess anything is useful.

For me, I'm on Windows 10, Edge 103. Sony's site connects me as En-Us (English, United States), which is true, I do reside in the US.

**Comment by finkleroy** [comment]
> > I'm able to successfully login using the second link you provided. I'm also able to login using the Playnite client, so it appears the issue is indeed with the Galaxy client. We'll need for GOG to fix it.
> 
> In the event GoG dev team sees this, what OS do you use, Which browser did you try it with, and what Region are you from? Any information we can provide may be useful. For region, the language/country code on Sony's website is likely enough, if you feel comfortable sharing it. Ideally, if you are testing via Firefox (i.e. not Chromium-based), that would be new information, but i guess anything is useful.
> 
> For me, I'm on Windows 10, Edge 103. Sony's site connects me as En-Us (English, United States), which is true, I do reside in the US.

Windows 10 (updated to the latest non-beta version), Chrome (updated), United States (English).

**Comment by juanimoli** [comment]
> A more technical note: Your login information is stored via a 64-bit cookie, known as a "session cookie". this cookie expires relatively quickly. However, there's a second cookie, called a "refresh cookie" that allows the caller to obtain a new "session cookie." After a period of two months of inactivity, the "refresh cookie" also expires. you will need to reauthenticate when that happens. if you access GoG Galaxy fairly often, this likely won't be an issue. The application checks if you have a session cookie, and if it has expired, attempts to retrieve a new one via the refresh cookie. if that has also expired, you need to log in again. The integration returns a "NextStep" object when this occurs. This tells the Galaxy to display a webpage (that URL in the previous comment), and, should you login successfully, take those cookies and pass them back to the plugin. The plugin never gets those cookies because the login never succeeds. The error you are seeing is most likely a security issue raised by PSN because the integrated browser Galaxy Client uses is out of date. I cannot confirm this because i do not have the source code for the client and do not know what integrated browser they use. It may also be an issue of PSN being down, either in your region or for maintenance.
> 
> I have submitted a bug report to GoG outlining this. If it is a browser issue, updating it would fix the issue. I'd like to test further, but upon trying earlier today, it suddenly worked again. The only thing i can suggest for now is to try logging in again later, but hopefully this can get fixed in the client.
> 
> Alternatively, you can try logging in via the link and manually copying the 64 bit cookie into the plugin.py authenticate function, but i really do not recommend this. It will expire very frequently and thus be pretty pointless. You also should only do so if you know what you're doing. I believe this method is outlined in the GoG Galaxy Integration page for this issue

@finkleroy got it working!

Based on this I went hunting that cookie cache. The first thing I saw is that it seems that Sony has changed 2FA screen (could be just frontend) and this means code changes, so cookie definitions could also have changed. As integration's name has "psn" and there is nothing of PS installed in this PC, I searched that string in Explorer. Found some folders, one was placed in "C:\ProgramData\GOG.com\Galaxy\webcache\". There should be a number folder and a "common" folder. Close GoG if opened and inside that number folder there should be a "psn" folder, **delete that one**. Re-open GoG and try again, it should be working now. I don't really know if when refresh token expires you can login again (haven't tried), but until devs see this, you can try this solution.

**Comment by finkleroy** [comment]
> > A more technical note: Your login information is stored via a 64-bit cookie, known as a "session cookie". this cookie expires relatively quickly. However, there's a second cookie, called a "refresh cookie" that allows the caller to obtain a new "session cookie." After a period of two months of inactivity, the "refresh cookie" also expires. you will need to reauthenticate when that happens. if you access GoG Galaxy fairly often, this likely won't be an issue. The application checks if you have a session cookie, and if it has expired, attempts to retrieve a new one via the refresh cookie. if that has also expired, you need to log in again. The integration returns a "NextStep" object when this occurs. This tells the Galaxy to display a webpage (that URL in the previous comment), and, should you login successfully, take those cookies and pass them back to the plugin. The plugin never gets those cookies because the login never succeeds. The error you are seeing is most likely a security issue raised by PSN because the integrated browser Galaxy Client uses is out of date. I cannot confirm this because i do not have the source code for the client and do not know what integrated browser they use. It may also be an issue of PSN being down, either in your region or for maintenance.
> > I have submitted a bug report to GoG outlining this. If it is a browser issue, updating it would fix the issue. I'd like to test further, but upon trying earlier today, it suddenly worked again. The only thing i can suggest for now is to try logging in again later, but hopefully this can get fixed in the client.
> > Alternatively, you can try logging in via the link and manually copying the 64 bit cookie into the plugin.py authenticate function, but i really do not recommend this. It will expire very frequently and thus be pretty pointless. You also should only do so if you know what you're doing. I believe this method is outlined in the GoG Galaxy Integration page for this issue
> 
> @finkleroy got it working!
> 
> Based on this I went hunting that cookie cache. The first thing I saw is that it seems that Sony has changed 2FA screen (could be just frontend) and this means code changes, so cookie definitions could also have changed. As integration's name has "psn" and there is nothing of PS installed in this PC, I searched that string in Explorer. Found some folders, one was placed in "C:\ProgramData\GOG.com\Galaxy\webcache". There should be a number folder and a "common" folder. Close GoG if opened and inside that number folder there should be a "psn" folder, **delete that one**. Re-open GoG and try again, it should be working now. I don't really know if when refresh token expires you can login again (haven't tried), but until devs see this, you can try this solution.

I just tried the workaround, but I'm still experiencing the same error. I don't know why it worked for you but not me. When I tried to login, it didn't re-create the psn folder, which I moved to my desktop instead of deleting.

**Comment by juanimoli** [comment]
> I just tried the workaround, but I'm still experiencing the same error. I don't know why it worked for you but not me. When I tried to login, it didn't re-create the psn folder, which I moved to my desktop instead of deleting.

I'm sad to hear that. You can try searching the same "psn" folder in your system or delete the whole "webcache" folder. Maybe you have it installed GoG twice in different locations (or drives) and you have multiple locations.

**Comment by BaumherA** [comment]
Deleting the web cache in theory could fix the error. It might also explain why it suddenly worked for me. Web browsers cache (store) data so the next time you visit a website it can load more quickly. If you happen to cache bad or outdated security data, PSN could (and likely should, because most security measures know they can be cracked after a long enough time and therefore expire before that point) invalidate itself. I have no idea what data the gog galaxy browser is caching or how to prevent it from caching in the first place, though I'm inclined to think that's not something we could do anyway

Tl;Dr: Try deleting everything in the web cache folder when GoG is closed. I believe it is located here: <code>C:/ProgramData/GOG.com/Galaxy/webcache</code>. It might cause gog to take longer to open back up, as gog caches the images/thumbnails for various games.

Edit: seeing you tried that already, you could try that in combination with deleting the psn integration. That is located in <code>%localappdata%</code> somewhere, not at my pc rn, apologies. Then when you start up GoG, add the psn integration back by going to settings -> (sync) integrations and then add integration, and search for psn.

**Comment by finkleroy** [comment]
> Deleting the web cache in theory could fix the error. It might also explain why it suddenly worked for me. Web browsers cache (store) data so the next time you visit a website it can load more quickly. If you happen to cache bad or outdated security data, PSN could (and likely should, because most security measures know they can be cracked after a long enough time and therefore expire before that point) invalidate itself. I have no idea what data the gog galaxy browser is caching or how to prevent it from caching in the first place, though I'm inclined to think that's not something we could do anyway
> 
> Tl;Dr: Try deleting everything in the web cache folder when GoG is closed. I believe it is located here: `C:/ProgramData/GOG.com/Galaxy/webcache`. It might cause gog to take longer to open back up, as gog caches the images/thumbnails for various games.
> 
> Edit: seeing you tried that already, you could try that in combination with deleting the psn integration. That is located in `%localappdata%` somewhere, not at my pc rn, apologies. Then when you start up GoG, add the psn integration back by going to settings -> (sync) integrations and then add integration, and search for psn.

I deleted everything related to PSN + GOG that was on volume C: and then added it again inside Galaxy, but I'm still getting the same error. This isn't the only Galaxy integration I'm having issues with, so I switched over to Playnite a short time ago. So far I haven't had any major issues with it, it's more lightweight, has more integrations and I like how it's set up better, so I'll just stick with it instead of going back to Galaxy. Thanks for trying to fix it.

**Comment by juanimoli** [comment]
> > Deleting the web cache in theory could fix the error. It might also explain why it suddenly worked for me. Web browsers cache (store) data so the next time you visit a website it can load more quickly. If you happen to cache bad or outdated security data, PSN could (and likely should, because most security measures know they can be cracked after a long enough time and therefore expire before that point) invalidate itself. I have no idea what data the gog galaxy browser is caching or how to prevent it from caching in the first place, though I'm inclined to think that's not something we could do anyway
> > Tl;Dr: Try deleting everything in the web cache folder when GoG is closed. I believe it is located here: `C:/ProgramData/GOG.com/Galaxy/webcache`. It might cause gog to take longer to open back up, as gog caches the images/thumbnails for various games.
> > Edit: seeing you tried that already, you could try that in combination with deleting the psn integration. That is located in `%localappdata%` somewhere, not at my pc rn, apologies. Then when you start up GoG, add the psn integration back by going to settings -> (sync) integrations and then add integration, and search for psn.
> 
> I deleted everything related to PSN + GOG that was on volume C: and then added it again inside Galaxy, but I'm still getting the same error. This isn't the only Galaxy integration I'm having issues with, so I switched over to Playnite a short time ago. So far I haven't had any major issues with it, it's more lightweight, has more integrations and I like how it's set up better, so I'll just stick with it instead of going back to Galaxy. Thanks for trying to fix it.

Are you sure you're deleting files from your current GoG installation? As I've said, from what I'm reading it sounds like you probably have or either two installations living in your system or just bad luck. If this isn't the case, then I'm afraid you will have to wait or use Playnite then. Hope any dev from GoG sees this.

**Comment by finkleroy** [comment]
> Are you sure you're deleting files from your current GoG installation? As I've said, from what I'm reading it sounds like you probably have or either two installations living in your system or just bad luck. If this isn't the case, then I'm afraid you will have to wait or use Playnite then. Hope any dev from GoG sees this.

I deleted all the files on volume C: that are related to PSN and Galaxy. The only PSN files I left are related to Playnite, RPCS3 and Steam.

**Comment by mcgowan7** [comment]
FYI I found a different tool that fills the need. So I don’t have to battle these unofficial plugins.

 

I moved to “Playnite”

 

Check it out. Works well.

 

-Mike

**Comment by philou-felin** [comment]
> FYI I found a different tool that fills the need. So I don’t have to battle these unofficial plugins. I moved to “Playnite” Check it out. Works well.

I think I'll just make a spreadsheet. 😆

That being said, if GOG doesn't manage to support PSN anymore, this might be bad in the future, as people decide they don't _really_ need GOG Galaxy, especially with offline installers... 🤷‍♂️

(sorry for multiple edits)
If GOG is not 100% working, and I still need Steam and EGS to launch games, _why_ would I keep the launcher? I also have troubles with itchIO, and many games, especially on EGS, are not listed in GOG... 🤷‍♂️

**Comment by Destroy666x** [comment]
@juanimoli thanks, that worked for me.

@philou-felin your comment doesn't make much sense as:
a) GOG never really supported PSN. This is unofficial integration made by someone and then forked.
b) Lots of other integtrations still work fine. For me only PSN was and Rockstar is broken.
c) It's also a standalone launcher for GOG games.
It's not going anywhere because of lack of support for PSN...

**Comment by philou-felin** [comment]
> @philou-felin your comment doesn't make much sense as: a) GOG never really supported PSN. This is unofficial integration made by someone and then forked. b) Lots of other integtrations still work fine. For me only PSN was and Rockstar is broken. c) It's also a standalone launcher for GOG games. It's not going anywhere because of lack of support for PSN...

Oh. Hey, I'm not wishing bad luck here. I was a bit annoyed, that is all. 😅 I knew this wasn't an official integration, but I didn't knew this was a fork from an existing/old integration.

**Comment by KyleStilkey** [comment]
I have been having this issue and thought it was just a normal PSN issue but after reading this I wanted to point out what worked for me for anyone in the future reading this that might not be very tech savvy. Make sure you shut off GOG first.

I had nothing for folders listed in C:/ProgramData/GOG.com/Galaxy/webcache for PSN, but I did have some located in the %localappdata%.

For people that do not know where this is or how to access with ease it's a hidden folder on your computer so you may need to turn on under the view options to see hidden folders but it would be located here C:\Users\(USER ACCOUNT)\AppData\Local\GOG.com\Galaxy\plugins\installed

In here was a PSN folder that was downloaded for the PSN integration. I deleted it and went back into GOG Settings, searched for playstation and downloaded the integration and it worked. It seems to be a common issue with GOG that it doesn't seem to update the integrations as I've had to do this with so many other ones over the years to fix problems like this.

I know this is a old bug report but I wanted to post this for anyone still having issues as I see in the forums this is still coming up a lot.

**Comment by Cyberinfosys** [comment]
Runing GOG in compatible mode of Windows 8 can solve this problem.

**Comment by EartHQuakE1974** [comment]
Found a (at least for me) working solution @ GOG forum

Source: https://www.gog.com/forum/general_beta_gog_galaxy_2.0/playstation_connection_timed_out/page39

1. Quit GOG Galaxy completely.

2. In your browser log in at store.playstation.com, then go to https://ca.account.sony.com/api/v1/ssocookie and copy the npsso value.

3. Open C:\Users\<username\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_<guid>\plugin.py in a text editor.

4. Replace line 52 ("return NextStep("web_session", AUTH_PARAMS)" with the following line (make sure to get the indentation correct: there's 12 spaces in front of the line):

stored_cookies = {"npsso": "<paste npsso value from browser here>"}

This line follows the "if not stored_cookies:" line on line 51

5. Save the file, restart Galaxy

6. Go to the settings and reconnect the PSN plugin 

So could we use this knowledge to create a valid pull request for the last release ? i am way out of my depth here, beeing a very rusty .Net developer i must admit. 

greets, earth

**Comment by gnoling** [comment]
As far as working solutions go, the earlier advice regarding Web Cache is spot on. Once that is cleared, it'll reconnect without issue.

**Comment by pippo-san** [comment]
Now, for some reason, the guys at playnite are having the same issue, and they discovered that pressing "Trouble with login?"  and then pressing the arrow button (previous page), will allow you to continue with the login, even with two-step autentication.

You can still replace the npsso value via code edit, but this one is easier :)

source: https://github.com/XenorPLxx/playnite-library-psn/issues/5#issuecomment-1268745292

**Comment by KZeni** [comment]
@pippo-san I attempted this method of going to "Trouble with login?", going back via the arrow at the top left, and then try to log in (per https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/40#issuecomment-1275993302), but I still got the same/similar error as others:
>A connection to the server could not be established.
>(18.b172117.1673387691.912cbdb)

I do have two-factor enabled, but it gives the error before showing the two-factor prompt (it rejects / doesn't proceed when submitting the password.)

Meanwhile, doing what @EartHQuakE1974 detailed in https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/40#issuecomment-1251114176 had me connected without ever seeing the login prompt after pressing connect (with it correctly connecting (then confirming it was correctly tied to my account & imported my library properly.) However, I'm left wondering how long this stays working before it needs to be given a new `npsso` value (then needing to repeat the editing of that python file with the new login cookie/auth value.)

So it seems there's still a valid workaround, but this really could/should be addressed formally. I'm not sure if there's a good way to have it do what https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/40#issuecomment-1251114176 does behind the scenes or anything (with the normal login prompt not working properly). Otherwise, couldn't this be updated to outright ask for the `npsso` value as a form field (with a link to https://ca.account.sony.com/api/v1/ssocookie & some instructions so the person establishing the connection can get the value they need) so we avoid the login as part of this integration entirely (putting it on one's web browser to log in [which must work for Sony's service to be functional] while it automates what's otherwise currently done by editing that file.)

**Comment by pippo-san** [comment]
>Otherwise, couldn't this be updated to outright ask for the `npsso` value as a form field (with a link to https://ca.account.sony.com/api/v1/ssocookie & some instructions so the person establishing the connection can get the value they need) so we avoid the login as part of this integration entirely (putting it on one's web browser to log in [which must work for Sony's service to be functional] while it automates what's otherwise currently done by editing that file.)

That's exactly what the guys at playnite are doing, the fact is that @FriendsOfGalaxy has been inactive for more than a year, and since he is the source for all the integrations available on galaxy we remain with an outdated mess right of the box.
I don't have time to look into it, if everyone else want to replace the login with just a field asking for the npsso go and do it :)

Anyway, once connected you won't have to retrieve the npsso value for quite a long time (like months, don't know when expires)

**Comment by s0ulmirr0r** [comment]
The npsso trick doesn't seems to work anymore, i can't connect to the server, maybe they changed the login url. Can someone verify? Thanks

**Comment by KZeni** [comment]
@s0ulmirr0r Going to https://ca.account.sony.com/api/v1/ssocookie returned my `npsso` value without issue just now, or is there a different part of the process that's breaking? Also, I did just use that for both the GOG `.py` file edit workaround from above a few days ago & with Playnite just yesterday without issue. GOG still shows it as connected & syncing integrations gave no errors just now, too.

**Comment by s0ulmirr0r** [comment]
> @s0ulmirr0r Going to https://ca.account.sony.com/api/v1/ssocookie returned my `npsso` value without issue just now, or is there a different part of the process that's breaking? Also, I did just use that for both the GOG `.py` file edit workaround from above a few days ago & with Playnite just yesterday without issue. GOG still shows it as connected & syncing integrations gave no errors just now, too.

I'm not sure what the issue is, it was working until a few days ago. I now deleted the plugin and the cache and reinstalled the integration. Replaced the line with the npsso i retrieved but after pressing connect it says "offline" retry. I checked the plugin.py file and everything seems correct. I'm stuck now.

**Comment by s0ulmirr0r** [comment]
> @s0ulmirr0r Going to https://ca.account.sony.com/api/v1/ssocookie returned my `npsso` value without issue just now, or is there a different part of the process that's breaking? Also, I did just use that for both the GOG `.py` file edit workaround from above a few days ago & with Playnite just yesterday without issue. GOG still shows it as connected & syncing integrations gave no errors just now, too.

My bad, i found the issue, there was a duplicate integration called playstation, deleted it and now the correct one (psn) is working with the npsso. I thought something has changed in the connection when i got the error, but it was my fault. Thanks anyway Kzeni, glad that the trick still works

**Comment by BaumherA** [comment]
Been a while since I've looked at this; finally logged back in to GOG and it reared its ugly head again. Seems PlayNite is having the same issue and has a copypasta workaround. Their solution was to avoid the API entirely and have you copy and paste the NPSSO directly into a text field instead of scraping it from the URL. [This comment](https://github.com/XenorPLxx/playnite-library-psn/issues/5#issuecomment-1299110559) explains why you'd occasionally be able to login before. The simple explanation: when you login to PSN, it can either go directly to PSN or to Akami, which acts as a middleman to prevent bots. Akami does not like GoG's browser (which i believe is because GoG's browser is outdated), and fails. 

The workaround I'm looking into is to avoid GoG's integrated browser entirely but still use the API. Some integrations of other applications will open your dedicated browser and do authentication there, then return to the app if it succeeds. Off the top of my head, i believe PayPal does this when opened from some mobile apps. I think i recall it doing this with EA Store (or whatever Origin is called now) on PC as well. It's not really how GoG's API is intended for use, but it could work. NGL i'm not really familiar with doing this (the whole point of GoG API was to do it for you), but we're basically doing OAuth already, so if there's a python library that can do an OAuth request in an external browser and keep the cookie jar, it'd solve this. The same approach could be used for PlayNite as well, except in C#, of course.

**Comment by joerg-nafcom** [comment]
I have the same issue and it appears the workarounds suggested here do not work for me

**Comment by ashleydb** [comment]
I wanted to try some of these workarounds in GOG Galaxy on Mac, but I can't find plugin.py. Closest I can find is: 

/Users/Shared/GOG.com/Galaxy/Storage/plugins/psn_38087aea-[blah blah blah]-storage.db
Trying to open that it seems to be binary and doesn't show anywhere to add the npsso.

I also checked here, but it only contains two folders; Epic and Xbox
/Applications/GOG Galaxy.app/Contents/Resources/Plugins

Any hints?

**Comment by ABaumher** [comment]
@ashleydb Try `~/Library/Application\ Support/GOG.com/Galaxy/plugins/installed`

Apparently `HOME/Library/Application Support` is the macOS equivalent of %localappdata%

**Comment by ashleydb** [comment]
First place I looked but weirdly the GOG.cpm folder (or anything similar)
doesn't exist.

**Comment by ABaumher** [comment]
Odd. That's where the documentation says it should be. Do you have any other extensions (steam, uplay, etc)? If so, are they in that folder?

Edit: Do you have a custom home path? IIRC macOS has HOME in a user folder, but you can configure that. Apologies, the last time i worked with macs was OSX (~~I think Big Sur? idr~~ El Capitan, so 2016. Geez, that was a while back. ). I'm going to need a VM of it to test the steam plugin, which is catestrophically broken for anyone not lucky enough to have signed in before steam changed the authentication. So i might be able to find it in a little bit, but i'm guessing you'd rather not wait that long

**Comment by ABaumher** [comment]
can you do a find or grep command from terminal? Grep searches the contents of the files and would be slower, but it's the one i'm familiar with. 

`grep -rn "class ProtocolClient"` or 
`find "protocol_client.py"` from whatever directory will search the most of your computer. 
Edit: you can specify the target folder to search with `-f <target/folder/location>` in `find`

**Comment by ashleydb** [comment]
I used this:
`find / -name "protocol_client.py" `
Which made me realize I was being dumb and ~/Library is within my User directory, but hidden. So, yes I do have this:
`/System/Volumes/Data/Users/<username>/Library/Application Support/GOG.com/Galaxy/plugins/installed/`
And there is a PSN folder in there with a plugin.py.
I'll try that. Thanks for the pointers.

**Comment by ashleydb** [comment]
Can confirm @EartHQuakE1974's [post above](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/40#issuecomment-1251114176) still works, even for my PSN account with 2FA enabled.

I just did it with GOG Galaxy version 2.0.62 (26) on an M1 Mac, editing this file using the Terminal (since Library seems to be a hidden folder):
/Users/<username>/Library/Application Support/GOG.com/Galaxy/plugins/installed/psn_38087aea-3c30-439f-867d-ddf9fae8fe6f/plugin.py

**Comment by Sin-Shadow-Fox** [comment]
> Found a (at least for me) working solution @ GOG forum
> 
> Source: https://www.gog.com/forum/general_beta_gog_galaxy_2.0/playstation_connection_timed_out/page39
> 
>     1. Quit GOG Galaxy completely.
> 
>     2. In your browser log in at store.playstation.com, then go to https://ca.account.sony.com/api/v1/ssocookie and copy the npsso value.
> 
>     3. Open C:\Users<username\AppData\Local\GOG.com\Galaxy\plugins\installed\psn_\plugin.py in a text editor.
> 
>     4. Replace line 52 ("return NextStep("web_session", AUTH_PARAMS)" with the following line (make sure to get the indentation correct: there's 12 spaces in front of the line):
> 
> 
> stored_cookies = {"npsso": ""}
> 
> This line follows the "if not stored_cookies:" line on line 51
> 
>     5. Save the file, restart Galaxy
> 
>     6. Go to the settings and reconnect the PSN plugin
> 
> 
> So could we use this knowledge to create a valid pull request for the last release ? i am way out of my depth here, beeing a very rusty .Net developer i must admit.
> 
> greets, earth

HTTP Status 429 – Too Many Requests

Type Status Report

Description The user has sent too many requests in a given amount of time ("rate limiting").
Apache Tomcat/9.0.34

**Comment by Kenyiro34** [comment]
> https://web.np.playstation.com/api/session/v1/signin?redirect_uri=https://io.playstation.com/central/auth/login%3FpostSignInURL=https://www.playstation.com/%26cancelURL=https://www.playstation.com/&smcid=web:pdc

Helo guys still got problem i got  wrong lines   i got 48 to 59 

48 async def authenticate(self, stored_credentials=None):
49       stored_cookies = stored_credentials.get("cookies") if stored_credentials else None
50        if not stored_cookies:
51           return NextStep("web_session", AUTH_PARAMS)
52
53       auth_info = await self._do_auth(stored_cookies)
54      return auth_info
55
56    async def pass_login_credentials(self, step, credentials, cookies):
57       cookies = {cookie["name"]: cookie["value"] for cookie in cookies}
58      self._store_cookies(cookies)
59     return await self._do_auth(cookies)

**Comment by Dilloid** [comment]
Tracking my combined playtime across all platforms is the only reason I use this stupid program. Absolutely worthless without this plugin, very annoying that they would abandon it.

**Comment by toptaran** [comment]
Hey guys, try my plugin update.

I fixed auth and added last time played.

I'm not python developer, but I will try to add time in game, achievements and other things in future releases. 

https://github.com/toptaran/galaxy-integration-psn

**Comment by Dilloid** [comment]
Fantastic work fixing authentication @toptaran! If we can get total play time/game time working that would be even better

**Comment by toptaran** [comment]
> Fantastic work fixing authentication [@toptaran](https://github.com/toptaran)! If we can get total play time/game time working that would be even better

I'm trying to backport psnawp, it's api for psn that support all of this and even more like achievements, friends. Problem is it's minimum python version is 3.10, but gog have 3.7 that's pretty old.

If it will be successful it will not be hard to add all things.

**Comment by toptaran** [comment]
@Dilloid added new release with support of play time/game time and achievements, try it.

https://github.com/toptaran/galaxy-integration-psn/releases/tag/v0.37

**Comment by Dilloid** [comment]
Trying this now

**Comment by Sin-Shadow-Fox** [comment]
> Trying this now

Please let the rest of us know if it works or not. And if there are any security issues.

**Comment by Dilloid** [comment]
It hasn't worked so far but it might be because my steam library is so big it's struggling to sync that first. I might log out of the steam connection and see if I can get it to work that way

**Comment by toptaran** [comment]
> It hasn't worked so far but it might be because my steam library is so big it's struggling to sync that first. I might log out of the steam connection and see if I can get it to work that way

it's already v0.38 released
https://github.com/toptaran/galaxy-integration-psn/releases/tag/v0.38

guys from gog forum confirmed it's working for them
https://www.gog.com/forum/general_beta_gog_galaxy_2.0/playstation_connection_timed_out/post700

**Comment by Dilloid** [comment]
I got it working, it requires manually applying this fix as mentioned in the gog forum thread: https://github.com/toptaran/galaxy-integration-psn/commit/3775a76d81303743099e20d415b2a63933807317

**Comment by toptaran** [comment]
> I got it working, it requires manually applying this fix as mentioned in the gog forum thread: [toptaran@3775a76](https://github.com/toptaran/galaxy-integration-psn/commit/3775a76d81303743099e20d415b2a63933807317)

Weird, i thought this bug can be get only with damaged cache, looks like smth more here. 
I only have 60+ games, so did not find this bug until reported.
Recreated v0.38 version including this fix.

**Comment by Sin-Shadow-Fox** [comment]
> > I got it working, it requires manually applying this fix as mentioned in the gog forum thread: [toptaran@3775a76](https://github.com/toptaran/galaxy-integration-psn/commit/3775a76d81303743099e20d415b2a63933807317)
> 
> Weird, i thought this bug can be get only with damaged cache, looks like smth more here. I only have 60+ games, so did not find this bug until reported. Recreated v0.38 version including this fix.

Followed [installation guide](https://github.com/toptaran/galaxy-integration-psn/blob/master/howto/INSTALL.md) to the letter. Installed the win7 version of .38. "Plugin has crashed. Retry."

**Comment by toptaran** [comment]
> > > I got it working, it requires manually applying this fix as mentioned in the gog forum thread: [toptaran@3775a76](https://github.com/toptaran/galaxy-integration-psn/commit/3775a76d81303743099e20d415b2a63933807317)
> > 
> > 
> > Weird, i thought this bug can be get only with damaged cache, looks like smth more here. I only have 60+ games, so did not find this bug until reported. Recreated v0.38 version including this fix.
> 
> Followed [installation guide](https://github.com/toptaran/galaxy-integration-psn/blob/master/howto/INSTALL.md) to the letter. Installed the win7 version of .38. "Plugin has crashed. Retry."

Try to find errors at logs c:\ProgramData\GOG.com\Galaxy\logs\ , find here plugin-psn-******.log

**Comment by Sin-Shadow-Fox** [comment]
> > > > I got it working, it requires manually applying this fix as mentioned in the gog forum thread: [toptaran@3775a76](https://github.com/toptaran/galaxy-integration-psn/commit/3775a76d81303743099e20d415b2a63933807317)
> > > 
> > > 
> > > Weird, i thought this bug can be get only with damaged cache, looks like smth more here. I only have 60+ games, so did not find this bug until reported. Recreated v0.38 version including this fix.
> > 
> > 
> > Followed [installation guide](https://github.com/toptaran/galaxy-integration-psn/blob/master/howto/INSTALL.md) to the letter. Installed the win7 version of .38. "Plugin has crashed. Retry."
> 
> Try to find errors at logs c:\ProgramData\GOG.com\Galaxy\logs\ , find here plugin-psn-******.log

[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/user-attachments/files/21956812/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by toptaran** [comment]
@Sin-Shadow-Fox checked your logs, i think you may incorrectly installed it, please attach screenshot of your psn plugin directory.

**Comment by Sin-Shadow-Fox** [comment]
> [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) checked your logs, i think you may incorrectly installed it, please attach screenshot of your psn plugin directory.

Whats that?

**Comment by toptaran** [comment]
> > [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) checked your logs, i think you may incorrectly installed it, please attach screenshot of your psn plugin directory.
> 
> Whats that?

Go to `%LocalAppData%\GOG.com\Galaxy\plugins\installed\`
Open the `psn_{random-id}` folder
Change view of folder to Details
Make screenshot of it contents and post here.

**Comment by Sin-Shadow-Fox** [comment]
> > > [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) checked your logs, i think you may incorrectly installed it, please attach screenshot of your psn plugin directory.
> > 
> > 
> > Whats that?
> 
> Go to `%LocalAppData%\GOG.com\Galaxy\plugins\installed\` Open the `psn_{random-id}` folder Change view of folder to Details Make screenshot of it contents and post here.

<img width="603" height="760" alt="Image" src="https://github.com/user-attachments/assets/9d35378b-3abc-4c9f-86ab-d7f89079452f" />

**Comment by toptaran** [comment]
Looks like unpacked files is corrupted, try to unpack windows_win7.zip using 7-zip, replace files again and test it.

**Comment by Sin-Shadow-Fox** [comment]
> Looks like unpacked files is corrupted, try to unpack windows_win7.zip using 7-zip, replace files again and test it.

How did you know i didn't use 7zip? Whats wrong with winrar? I've been using it without problem for years.

**Comment by toptaran** [comment]
> > Looks like unpacked files is corrupted, try to unpack windows_win7.zip using 7-zip, replace files again and test it.
> 
> How did you know i didn't use 7zip? Whats wrong with winrar? I've been using it without problem for years.

I did not, just know sometimes other archivers can corrupt files when unpack zip archives. So I recommend to try 7-zip.

**Comment by Sin-Shadow-Fox** [comment]
> > > Looks like unpacked files is corrupted, try to unpack windows_win7.zip using 7-zip, replace files again and test it.
> > 
> > 
> > How did you know i didn't use 7zip? Whats wrong with winrar? I've been using it without problem for years.
> 
> I did not, just know sometimes other archivers can corrupt files when unpack zip archives. So I recommend to try 7-zip.

Ok so . . . i . . .didn't do what you asked. Instead i deviated from your instructions and it seems to have work (kinda). Instead of replacing the files in that psn folder with your files like your instructions say, i instead deleted all the files in there first then just pasted your files in there and i got a different result.

<img width="1333" height="784" alt="Image" src="https://github.com/user-attachments/assets/18069f5a-b087-4319-9151-ef061319d8ab" />

**Comment by toptaran** [comment]
> > > > Looks like unpacked files is corrupted, try to unpack windows_win7.zip using 7-zip, replace files again and test it.
> > > 
> > > 
> > > How did you know i didn't use 7zip? Whats wrong with winrar? I've been using it without problem for years.
> > 
> > 
> > I did not, just know sometimes other archivers can corrupt files when unpack zip archives. So I recommend to try 7-zip.
> 
> Ok so . . . i . . .didn't do what you asked. Instead i deviated from your instructions and it seems to have work (kinda). Instead of replacing the files in that psn folder with your files like your instructions say, i instead deleted all the files in there first then just pasted your files in there and i got a different result.
> <img alt="Image" width="1333" height="784" src="https://private-user-images.githubusercontent.com/96899282/481711623-18069f5a-b087-4319-9151-ef061319d8ab.PNG?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNTE0NjEsIm5iZiI6MTc1NjE1MTE2MSwicGF0aCI6Ii85Njg5OTI4Mi80ODE3MTE2MjMtMTgwNjlmNWEtYjA4Ny00MzE5LTkxNTEtZWYwNjEzMTlkOGFiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI1VDE5NDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OTE2NGU5ODY5MWViNWI3OThlZGU3NmU4YjUzOWRhMDU3OTFiM2RjYjliYjMxYzNkY2Y3NTUyN2VkZTVhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2SPcc1pYdivAK7LNRh9ufQDccC42-bjW4BkCAlqzUyk">

Tested on clean win 7, have same problem, I'll think on solution.

**Comment by Sin-Shadow-Fox** [comment]
> > > > > Looks like unpacked files is corrupted, try to unpack windows_win7.zip using 7-zip, replace files again and test it.
> > > > 
> > > > 
> > > > How did you know i didn't use 7zip? Whats wrong with winrar? I've been using it without problem for years.
> > > 
> > > 
> > > I did not, just know sometimes other archivers can corrupt files when unpack zip archives. So I recommend to try 7-zip.
> > 
> > 
> > Ok so . . . i . . .didn't do what you asked. Instead i deviated from your instructions and it seems to have work (kinda). Instead of replacing the files in that psn folder with your files like your instructions say, i instead deleted all the files in there first then just pasted your files in there and i got a different result.
> > <img alt="Image" width="1333" height="784" src="https://private-user-images.githubusercontent.com/96899282/481711623-18069f5a-b087-4319-9151-ef061319d8ab.PNG?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxNTE0NjEsIm5iZiI6MTc1NjE1MTE2MSwicGF0aCI6Ii85Njg5OTI4Mi80ODE3MTE2MjMtMTgwNjlmNWEtYjA4Ny00MzE5LTkxNTEtZWYwNjEzMTlkOGFiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI1VDE5NDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OTE2NGU5ODY5MWViNWI3OThlZGU3NmU4YjUzOWRhMDU3OTFiM2RjYjliYjMxYzNkY2Y3NTUyN2VkZTVhNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2SPcc1pYdivAK7LNRh9ufQDccC42-bjW4BkCAlqzUyk">
> 
> Tested on clean win 7, have same problem, I'll think on solution.

It might also be a good idea to edit the [instructions page](https://github.com/toptaran/galaxy-integration-psn/blob/master/howto/INSTALL.md)

<img width="1899" height="855" alt="Image" src="https://github.com/user-attachments/assets/451dc99d-8cf4-4cd1-887a-d26553881d8c" />

to say delete, copy, paste instead of copy, paste, replace just so other people don't run into the same problem i did.
I think the reason replacing doesn't work is because it leaves behind files that you don't have a replacement for and that messes with the program.

**Comment by toptaran** [comment]
@Sin-Shadow-Fox created new release v0.39, try it.

https://github.com/toptaran/galaxy-integration-psn/releases/tag/v0.39

**Comment by Sin-Shadow-Fox** [comment]
> [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) created new release v0.39, try it.
> 
> https://github.com/toptaran/galaxy-integration-psn/releases/tag/v0.39

<img width="799" height="575" alt="Image" src="https://github.com/user-attachments/assets/2976b887-8c24-46f7-b5fa-35a4d30eeeb0" />

**Comment by toptaran** [comment]
@Sin-Shadow-Fox So? After you give it token it will need like 10-15seconds to fetch account data.

**Comment by Sin-Shadow-Fox** [comment]
> [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) So? After you give it token it will need like 10-15seconds to fetch account data.

It didn't ask for a token or a login. And it's been doing that for an hour.

**Comment by toptaran** [comment]
> > [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) So? After you give it token it will need like 10-15seconds to fetch account data.
> 
> It didn't ask for a token or a login. And it's been doing that for an hour.

Well, that's weird, I tested it myself on fresh installed windows 7. Try to restart gog and test again. If in 1 minute it will not work, send logs again.

**Comment by Sin-Shadow-Fox** [comment]
> > > [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) So? After you give it token it will need like 10-15seconds to fetch account data.
> > 
> > 
> > It didn't ask for a token or a login. And it's been doing that for an hour.
> 
> Well, that's weird, I tested it myself on fresh installed windows 7. Try to restart gog and test again. If in 1 minute it will not work, send logs again.

No idea why but restarting after the first failure worked.

<img width="1611" height="953" alt="Image" src="https://github.com/user-attachments/assets/45898edc-61ce-4ea0-b6eb-28fdc1ce775c" />

Also fuck that NPSSO token process, lol. But hey, it worked ^_^

**Comment by toptaran** [comment]
> > > > [@Sin-Shadow-Fox](https://github.com/Sin-Shadow-Fox) So? After you give it token it will need like 10-15seconds to fetch account data.
> > > 
> > > 
> > > It didn't ask for a token or a login. And it's been doing that for an hour.
> > 
> > 
> > Well, that's weird, I tested it myself on fresh installed windows 7. Try to restart gog and test again. If in 1 minute it will not work, send logs again.
> 
> No idea why but restarting after the first failure worked.
> <img alt="Image" width="1611" height="953" src="https://private-user-images.githubusercontent.com/96899282/482230374-45898edc-61ce-4ea0-b6eb-28fdc1ce775c.PNG?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyMzI0NjYsIm5iZiI6MTc1NjIzMjE2NiwicGF0aCI6Ii85Njg5OTI4Mi80ODIyMzAzNzQtNDU4OThlZGMtNjFjZS00ZWEwLWI2ZWItMjhmZGMxY2U3NzVjLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDE4MTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxOWY5MGE2NzIzNzE1MWUxM2VlMjkxMGEzZDAzZDlhZTc2MjRhODQzZTNiZGYyZTU0MjYwYjgyNTk5NWRmNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FinGkvrGctXWNdJkMuMhHrP3EAOnr4MwV8nUoPUgcEI">
> 
> Also fuck that NPSSO token process, lol. But hey, it worked ^_^

Yeah, I did try to make that cefpython plugin work on win7 but have no luck. Otherwise NPSSO token is solid thing and year later sony can forbid even this new(old) cef for win7, but NPSSO will still work.
